// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8LmEKCG-68wr8b3mor2y72QZsiAmc_xQ',
    appId: '1:411033480666:web:f10b2d88e161449a0464e3',
    messagingSenderId: '411033480666',
    projectId: 'weechat-caabb',
    authDomain: 'weechat-caabb.firebaseapp.com',
    storageBucket: 'weechat-caabb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBKZqrjFnaIeWYeFU-57W3__70oJKUkw',
    appId: '1:411033480666:android:e2acc51a0918b0500464e3',
    messagingSenderId: '411033480666',
    projectId: 'weechat-caabb',
    storageBucket: 'weechat-caabb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzkLFrdNWvI0xEJ5f1wmFwDSp9z8ai9C8',
    appId: '1:411033480666:ios:2518b3572e62f5010464e3',
    messagingSenderId: '411033480666',
    projectId: 'weechat-caabb',
    storageBucket: 'weechat-caabb.appspot.com',
    androidClientId: '411033480666-pmodqurpfcsfulck3g9btl58qe9h8it5.apps.googleusercontent.com',
    iosClientId: '411033480666-abe4812pdihnbugkdrup7q890jhp7r54.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
